export const FETCH_BLOGS_STARTED = "FETCH_BLOGS_STARTED";
export const FETCH_BLOGS_SUCCEEDED = "FETCH_BLOGS_SUCCEEDED";
export const FETCH_BLOGS_REJECTED = "FETCH_BLOGS_REJECTED";

export const FETCH_BLOG_STARTED = "FETCH_BLOG_STARTED";
export const FETCH_BLOG_SUCCEEDED = "FETCH_BLOG_SUCCEEDED";
export const FETCH_BLOG_REJECTED = "FETCH_BLOG_REJECTED";

export const ADD_BLOG_STARTED = "ADD_BLOG_STARTED";
export const ADD_BLOG_SUCCEEDED = "ADD_BLOG_SUCCEEDED";
export const ADD_BLOG_REJECTED = "ADD_BLOG_REJECTED";

export const DELETE_BLOG_STARTED = "DELETE_BLOG_STARTED";
export const DELETE_BLOG_SUCCEEDED = "DELETE_BLOG_SUCCEEDED";
export const DELETE_BLOG_REJECTED = "DELETE_BLOG_REJECTED";

export const TOGGLE_URL_LOCK = "TOGGLE_URL_LOCK";
export const SET_URL_TEXT = "SET_URL_TEXT";



